export enum JoiEnum {
    IS_REQUIRED_OR_INVALID = 'IS_REQUIRED_OR_INVALID',
    INVALID = 'INVALID',
    REQUIRED = 'REQUIRED',
    MUST_BE_MATCHING_PW = 'MUST_BE_MATCHING_PW',
    MUST_BE_CORRECT_WITH_REQUIREMENTS = 'MUST_BE_CORRECT_WITH_REQUIREMENTS',
}
