FROM node:20.15.1

WORKDIR /app

COPY package*.json .

RUN apt-get update && apt-get install -y \
    build-essential \
    libssl-dev \
    libsodium-dev \
    && rm -rf /var/lib/apt/lists/*

RUN npm install --force

COPY . .

RUN npm run build

EXPOSE 3000

CMD ["npm", "run", "start:prod"]
